# Setup
title: Fluffy Mods
tagline: "Its so fluffyyy!"
description: "Random thoughts"
url: https://fluffy-mods.github.io/
baseurl: ""
paginate: 5
permalink: pretty

# About/contact
author:
  name: Fluffy
  email: fluffy.l2032@gmail.com
  github: FluffierThanThou

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version: 1.1.0
google_analytics_id: #UA-XXXX-Y
